usethis::use_mit_license()
usethis::use_build_ignore("dev_history.R")
attachment::att_amend_desc()
devtools::check()
usethis::use_readme_md()
usethis::use_vignette('ab-Plotting_castles')
usethis::use_package("here")
usethis::use_package("qpdf")
usethis::use_pipe()
devtools::document()
usethis::use_data_raw(name = "Scottish_castles_locations")
usethis::use_package("dplyr")
usethis::use_package("sf")
usethis::use_package("stringr")
usethis::use_package("raster")
devtools::check()
usethis::use_vignette(name = "Plotting_Scottish_castles", title = "Plotting Scottish castles")
usethis::use_r("clean_names_castles")
devtools::document()
usethis::use_r("merge_castles")
devtools::document()
usethis::use_package("png")
usethis::use_package("plyr")
usethis::use_package("tidyr")
usethis::use_package("showtext")
usethis::use_package("ggplot2")
usethis::use_package("MetBrewer")
usethis::use_package("ggimage")
usethis::use_package("ggpubr")
usethis::use_package("ggspatial")
usethis::use_package("ragg")

