usethis::use_mit_license()
usethis::use_build_ignore("dev_history.R")
attachment::att_amend_desc()
devtools::check()
usethis::use_readme_md()
usethis::use_vignette('ab-Plotting_castles')
usethis::use_package("here")
usethis::use_package("qpdf")
usethis::use_pipe()
devtools::document()
usethis::use_data_raw(name = "Scottish_castles_locations")
usethis::use_package("dplyr")
usethis::use_package("sf")
usethis::use_package("stringr")
usethis::use_package("raster")
devtools::check()
usethis::use_vignette(name = "Plotting_Scottish_castles", title = "Plotting Scottish castles")
usethis::use_r("clean_names_castles")
devtools::document()
usethis::use_r("merge_castles")
devtools::document()
usethis::use_package("png")
usethis::use_package("plyr")
usethis::use_package("tidyr")
usethis::use_package("showtext")
usethis::use_package("ggplot2")
usethis::use_package("MetBrewer")
usethis::use_package("ggimage")
usethis::use_package("ggpubr")
usethis::use_package("ggspatial")
usethis::use_package("ragg")
usethis::use_testthat(3)
usethis::use_test("clean_names_castles")
testthat::test_file("test-clean_names_castles")
usethis::use_test("merging_castles")
testthat::test_file("test-merging_castles")
devtools::test()
devtools::test_coverage()
usethis::use_package("rlang")  #when calling a variable name in a function
usethis::use_import_from("rlang", c(".data", ".env"))
usethis::use_package("tibble")

#to remove warning about no visible binding for global variables
library(checkhelper)
checkhelper::find_missing_tags()
globals <- get_no_visible(quiet = TRUE)
print_globals(globals)
usethis::use_r("globals")
